// Auto-generated by 10_dashboard_data.R. Do not edit by hand.
const DASH = {
  "meta": {
    "nCountries": 199,
    "nElections": 3644,
    "nCountryYears": 11763,
    "yearMin": 1945,
    "yearMax": 2026,
    "generated": "2026-08-17"
  },
  "regimes": ["Closed autocracy", "Electoral autocracy", "Electoral democracy", "Liberal democracy"],
  "countries": [
    {
      "c": "Afghanistan",
      "iso": "AFG",
      "reg": 1,
      "f": 2.48,
      "t": 45.8,
      "p": 0.14,
      "poly": 0.309
    },
    {
      "c": "Angola",
      "iso": "AGO",
      "reg": 1,
      "f": 1.19,
      "t": 73.9,
      "p": -0.21,
      "poly": 0.239
    },
    {
      "c": "Albania",
      "iso": "ALB",
      "reg": 2,
      "f": 2.76,
      "t": 50.9,
      "p": -1.37,
      "poly": 0.517
    },
    {
      "c": "Andorra",
      "iso": "AND",
      "reg": null,
      "f": 2.86,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Argentina",
      "iso": "ARG",
      "reg": 2,
      "f": 4.9,
      "t": 76,
      "p": 1.1,
      "poly": 0.787
    },
    {
      "c": "Armenia",
      "iso": "ARM",
      "reg": 1,
      "f": 4.43,
      "t": 61.5,
      "p": 0.88,
      "poly": 0.404
    },
    {
      "c": "Antigua & Barbuda",
      "iso": "ATG",
      "reg": null,
      "f": 2.05,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Australia",
      "iso": "AUS",
      "reg": 3,
      "f": 3.43,
      "t": 93.3,
      "p": -1.15,
      "poly": 0.875
    },
    {
      "c": "Austria",
      "iso": "AUT",
      "reg": 3,
      "f": 4.62,
      "t": 74.6,
      "p": -0.49,
      "poly": 0.866
    },
    {
      "c": "Azerbaijan",
      "iso": "AZE",
      "reg": 1,
      "f": 5.1,
      "t": 61.4,
      "p": 0.39,
      "poly": 0.213
    },
    {
      "c": "Burundi",
      "iso": "BDI",
      "reg": 1,
      "f": 2.33,
      "t": 79.1,
      "p": 1.5,
      "poly": 0.255
    },
    {
      "c": "Belgium",
      "iso": "BEL",
      "reg": 3,
      "f": 2.57,
      "t": 89.9,
      "p": -1.85,
      "poly": 0.896
    },
    {
      "c": "Benin",
      "iso": "BEN",
      "reg": 2,
      "f": 4.52,
      "t": 65.5,
      "p": -1.04,
      "poly": 0.612
    },
    {
      "c": "Burkina Faso",
      "iso": "BFA",
      "reg": 2,
      "f": 3.52,
      "t": 60,
      "p": -0.76,
      "poly": 0.564
    },
    {
      "c": "Bangladesh",
      "iso": "BGD",
      "reg": 1,
      "f": 2,
      "t": 72.9,
      "p": 1.15,
      "poly": 0.364
    },
    {
      "c": "Bulgaria",
      "iso": "BGR",
      "reg": 2,
      "f": 4.95,
      "t": 54.8,
      "p": -1.19,
      "poly": 0.677
    },
    {
      "c": "Bahrain",
      "iso": "BHR",
      "reg": 0,
      "f": 1.9,
      "t": 62.3,
      "p": 1.46,
      "poly": 0.165
    },
    {
      "c": "Bahamas",
      "iso": "BHS",
      "reg": null,
      "f": 2,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Bosnia and Herzegovina",
      "iso": "BIH",
      "reg": 2,
      "f": 3.05,
      "t": 55.8,
      "p": 1.26,
      "poly": 0.585
    },
    {
      "c": "Belarus",
      "iso": "BLR",
      "reg": 1,
      "f": 4.38,
      "t": 81.2,
      "p": 1.24,
      "poly": 0.24
    },
    {
      "c": "Belize",
      "iso": "BLZ",
      "reg": null,
      "f": 2.24,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Bolivia",
      "iso": "BOL",
      "reg": 2,
      "f": 3.33,
      "t": 85.7,
      "p": 0.91,
      "poly": 0.663
    },
    {
      "c": "Brazil",
      "iso": "BRA",
      "reg": 2,
      "f": 2.48,
      "t": 81.5,
      "p": 0.04,
      "poly": 0.837
    },
    {
      "c": "Barbados",
      "iso": "BRB",
      "reg": 2,
      "f": 2.14,
      "t": 61.4,
      "p": -3.39,
      "poly": 0.776
    },
    {
      "c": "Bhutan",
      "iso": "BTN",
      "reg": 2,
      "f": 3,
      "t": 72.3,
      "p": -1.3,
      "poly": 0.55
    },
    {
      "c": "Botswana",
      "iso": "BWA",
      "reg": 3,
      "f": 2,
      "t": 80.2,
      "p": -1.81,
      "poly": 0.696
    },
    {
      "c": "Central African Republic",
      "iso": "CAF",
      "reg": 1,
      "f": 2.57,
      "t": 58.1,
      "p": 0.88,
      "poly": 0.329
    },
    {
      "c": "Canada",
      "iso": "CAN",
      "reg": 3,
      "f": 3.24,
      "t": 63.3,
      "p": -1.41,
      "poly": 0.831
    },
    {
      "c": "Switzerland",
      "iso": "CHE",
      "reg": 3,
      "f": 2.52,
      "t": 47.2,
      "p": -1.75,
      "poly": 0.897
    },
    {
      "c": "Chile",
      "iso": "CHL",
      "reg": 3,
      "f": 4.33,
      "t": 77.8,
      "p": -1.5,
      "poly": 0.881
    },
    {
      "c": "Cote d'Ivoire",
      "iso": "CIV",
      "reg": 1,
      "f": 3.43,
      "t": 49.8,
      "p": 1.03,
      "poly": 0.458
    },
    {
      "c": "Cameroon",
      "iso": "CMR",
      "reg": 1,
      "f": 3.71,
      "t": 64.2,
      "p": 1.13,
      "poly": 0.312
    },
    {
      "c": "Congo, Democratic Republic of",
      "iso": "COD",
      "reg": 1,
      "f": 1.1,
      "t": 58.3,
      "p": 0.86,
      "poly": 0.288
    },
    {
      "c": "Congo",
      "iso": "COG",
      "reg": 1,
      "f": 3.1,
      "t": 62.7,
      "p": 0.21,
      "poly": 0.243
    },
    {
      "c": "Colombia",
      "iso": "COL",
      "reg": 2,
      "f": 5,
      "t": 48.4,
      "p": 0.78,
      "poly": 0.617
    },
    {
      "c": "Comoros",
      "iso": "COM",
      "reg": 1,
      "f": 3.86,
      "t": 66.2,
      "p": 0.71,
      "poly": 0.401
    },
    {
      "c": "Cabo Verde",
      "iso": "CPV",
      "reg": 2,
      "f": 3.95,
      "t": 63.8,
      "p": -0.88,
      "poly": 0.785
    },
    {
      "c": "Costa Rica",
      "iso": "CRI",
      "reg": 3,
      "f": 2.48,
      "t": 67.6,
      "p": -1.42,
      "poly": 0.902
    },
    {
      "c": "Cuba",
      "iso": "CUB",
      "reg": 0,
      "f": 2,
      "t": 92.8,
      "p": -0.45,
      "poly": 0.146
    },
    {
      "c": "Cyprus",
      "iso": "CYP",
      "reg": 3,
      "f": 4,
      "t": 83.1,
      "p": 0.36,
      "poly": 0.832
    },
    {
      "c": "Czech Republic",
      "iso": "CZE",
      "reg": 3,
      "f": 7.67,
      "t": 62.3,
      "p": -1.73,
      "poly": 0.873
    },
    {
      "c": "German Federal Republic",
      "iso": "DEU",
      "reg": 3,
      "f": 2.57,
      "t": 75,
      "p": -2.06,
      "poly": 0.894
    },
    {
      "c": "Djibouti",
      "iso": "DJI",
      "reg": 1,
      "f": 3.67,
      "t": 67.9,
      "p": 0.19,
      "poly": 0.249
    },
    {
      "c": "Dominica",
      "iso": "DMA",
      "reg": null,
      "f": 1.76,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Denmark",
      "iso": "DNK",
      "reg": 3,
      "f": 2.86,
      "t": 86.1,
      "p": -3,
      "poly": 0.918
    },
    {
      "c": "Dominican Republic",
      "iso": "DOM",
      "reg": 2,
      "f": 4.43,
      "t": 64.4,
      "p": -0.36,
      "poly": 0.613
    },
    {
      "c": "Algeria",
      "iso": "DZA",
      "reg": 1,
      "f": 4,
      "t": 48,
      "p": -1.19,
      "poly": 0.32
    },
    {
      "c": "Ecuador",
      "iso": "ECU",
      "reg": 2,
      "f": 3.76,
      "t": 76.5,
      "p": 1.08,
      "poly": 0.626
    },
    {
      "c": "Egypt",
      "iso": "EGY",
      "reg": 1,
      "f": 5.43,
      "t": 40.5,
      "p": -0.18,
      "poly": 0.199
    },
    {
      "c": "Spain",
      "iso": "ESP",
      "reg": 3,
      "f": 3.05,
      "t": 72.5,
      "p": -1.17,
      "poly": 0.875
    },
    {
      "c": "Estonia",
      "iso": "EST",
      "reg": 3,
      "f": 2.57,
      "t": 62.3,
      "p": -1.36,
      "poly": 0.882
    },
    {
      "c": "Ethiopia",
      "iso": "ETH",
      "reg": 1,
      "f": 2.14,
      "t": 89.8,
      "p": 0.81,
      "poly": 0.247
    },
    {
      "c": "Finland",
      "iso": "FIN",
      "reg": 3,
      "f": 4.24,
      "t": 69.6,
      "p": -1.5,
      "poly": 0.878
    },
    {
      "c": "Fiji",
      "iso": "FJI",
      "reg": 1,
      "f": 2.14,
      "t": 75.4,
      "p": -0.67,
      "poly": 0.308
    },
    {
      "c": "France",
      "iso": "FRA",
      "reg": 3,
      "f": 3.86,
      "t": 80.4,
      "p": 0.11,
      "poly": 0.88
    },
    {
      "c": "Federated States of Micronesia",
      "iso": "FSM",
      "reg": null,
      "f": 4.62,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Gabon",
      "iso": "GAB",
      "reg": 1,
      "f": 3.57,
      "t": 52,
      "p": -0.66,
      "poly": 0.363
    },
    {
      "c": "United Kingdom",
      "iso": "GBR",
      "reg": 3,
      "f": 2.43,
      "t": 64.8,
      "p": -0.63,
      "poly": 0.864
    },
    {
      "c": "Georgia",
      "iso": "GEO",
      "reg": 2,
      "f": 4.86,
      "t": 61.2,
      "p": 1.16,
      "poly": 0.545
    },
    {
      "c": "Ghana",
      "iso": "GHA",
      "reg": 3,
      "f": 2.62,
      "t": 74.4,
      "p": -0.47,
      "poly": 0.739
    },
    {
      "c": "Guinea",
      "iso": "GIN",
      "reg": 1,
      "f": 2.95,
      "t": 72.2,
      "p": 1.27,
      "poly": 0.295
    },
    {
      "c": "Gambia",
      "iso": "GMB",
      "reg": 1,
      "f": 3.95,
      "t": 56.2,
      "p": -0.66,
      "poly": 0.299
    },
    {
      "c": "Guinea-Bissau",
      "iso": "GNB",
      "reg": 1,
      "f": 3.95,
      "t": 75.7,
      "p": -0.79,
      "poly": 0.442
    },
    {
      "c": "Equatorial Guinea",
      "iso": "GNQ",
      "reg": 1,
      "f": 3.57,
      "t": 92.9,
      "p": 0.86,
      "poly": 0.182
    },
    {
      "c": "Greece",
      "iso": "GRC",
      "reg": 3,
      "f": 3.86,
      "t": 69,
      "p": -1.09,
      "poly": 0.883
    },
    {
      "c": "Grenada",
      "iso": "GRD",
      "reg": null,
      "f": 2.14,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Guatemala",
      "iso": "GTM",
      "reg": 2,
      "f": 3,
      "t": 63.6,
      "p": -0.7,
      "poly": 0.579
    },
    {
      "c": "Guyana",
      "iso": "GUY",
      "reg": 2,
      "f": 2.19,
      "t": 75.6,
      "p": 1.15,
      "poly": 0.597
    },
    {
      "c": "Honduras",
      "iso": "HND",
      "reg": 1,
      "f": 2.48,
      "t": 58.4,
      "p": -0.74,
      "poly": 0.467
    },
    {
      "c": "Croatia",
      "iso": "HRV",
      "reg": 2,
      "f": 5.67,
      "t": 55.3,
      "p": 0.42,
      "poly": 0.787
    },
    {
      "c": "Haiti",
      "iso": "HTI",
      "reg": 1,
      "f": 4.05,
      "t": 38.3,
      "p": 0.99,
      "poly": 0.398
    },
    {
      "c": "Hungary",
      "iso": "HUN",
      "reg": 2,
      "f": 2.48,
      "t": 67.4,
      "p": 1.34,
      "poly": 0.735
    },
    {
      "c": "Indonesia",
      "iso": "IDN",
      "reg": 2,
      "f": 3.52,
      "t": 78.3,
      "p": 0.65,
      "poly": 0.668
    },
    {
      "c": "India",
      "iso": "IND",
      "reg": 2,
      "f": 2.52,
      "t": 62.5,
      "p": 0.44,
      "poly": 0.636
    },
    {
      "c": "Ireland",
      "iso": "IRL",
      "reg": 3,
      "f": 3.1,
      "t": 61.9,
      "p": -3.37,
      "poly": 0.893
    },
    {
      "c": "Iran",
      "iso": "IRN",
      "reg": 1,
      "f": 5.33,
      "t": 63.3,
      "p": 0.98,
      "poly": 0.186
    },
    {
      "c": "Iraq",
      "iso": "IRQ",
      "reg": 1,
      "f": 2.9,
      "t": 72.7,
      "p": 1.8,
      "poly": 0.341
    },
    {
      "c": "Iceland",
      "iso": "ISL",
      "reg": 3,
      "f": 4.9,
      "t": 77.5,
      "p": -0.77,
      "poly": 0.871
    },
    {
      "c": "Israel",
      "iso": "ISR",
      "reg": 3,
      "f": 3.24,
      "t": 67.7,
      "p": 0.56,
      "poly": 0.748
    },
    {
      "c": "Italy",
      "iso": "ITA",
      "reg": 3,
      "f": 2.52,
      "t": 78.7,
      "p": 0.23,
      "poly": 0.857
    },
    {
      "c": "Jamaica",
      "iso": "JAM",
      "reg": 2,
      "f": 2.19,
      "t": 51.5,
      "p": -1.32,
      "poly": 0.772
    },
    {
      "c": "Jordan",
      "iso": "JOR",
      "reg": 0,
      "f": 2.57,
      "t": 47.9,
      "p": -1.04,
      "poly": 0.236
    },
    {
      "c": "Japan",
      "iso": "JPN",
      "reg": 3,
      "f": 6.24,
      "t": 60.4,
      "p": -1.9,
      "poly": 0.842
    },
    {
      "c": "Kazakhstan",
      "iso": "KAZ",
      "reg": 1,
      "f": 4.48,
      "t": 77.1,
      "p": -0.49,
      "poly": 0.242
    },
    {
      "c": "Kenya",
      "iso": "KEN",
      "reg": 1,
      "f": 2.14,
      "t": 72.9,
      "p": 0.22,
      "poly": 0.475
    },
    {
      "c": "Kyrgyz Republic",
      "iso": "KGZ",
      "reg": 1,
      "f": 4.86,
      "t": 66,
      "p": -0.33,
      "poly": 0.375
    },
    {
      "c": "Cambodia",
      "iso": "KHM",
      "reg": 1,
      "f": 2,
      "t": 77.5,
      "p": 0.04,
      "poly": 0.291
    },
    {
      "c": "Kiribati",
      "iso": "KIR",
      "reg": null,
      "f": 5.38,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Saint Kitts and Nevis",
      "iso": "KNA",
      "reg": null,
      "f": 2.1,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Korea, Republic of",
      "iso": "KOR",
      "reg": 3,
      "f": 4.52,
      "t": 63.8,
      "p": 0.17,
      "poly": 0.804
    },
    {
      "c": "Kuwait",
      "iso": "KWT",
      "reg": 0,
      "f": 4.24,
      "t": 64.5,
      "p": -1.4,
      "poly": 0.311
    },
    {
      "c": "Lao People's Dem. Republic",
      "iso": "LAO",
      "reg": 0,
      "f": 2.1,
      "t": 99.3,
      "p": -0.52,
      "poly": 0.097
    },
    {
      "c": "Lebanon",
      "iso": "LBN",
      "reg": 1,
      "f": 1.95,
      "t": 48.8,
      "p": 1.09,
      "poly": 0.435
    },
    {
      "c": "Liberia",
      "iso": "LBR",
      "reg": 2,
      "f": 1.86,
      "t": 74.4,
      "p": 0.33,
      "poly": 0.541
    },
    {
      "c": "Libya",
      "iso": "LBY",
      "reg": 0,
      "f": 1.1,
      "t": 55.6,
      "p": 1.38,
      "poly": 0.179
    },
    {
      "c": "Saint Lucia",
      "iso": "LCA",
      "reg": null,
      "f": 2.1,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Liechtenstein",
      "iso": "LIE",
      "reg": null,
      "f": 2.62,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Sri Lanka",
      "iso": "LKA",
      "reg": 1,
      "f": 4.1,
      "t": 77,
      "p": 0.43,
      "poly": 0.474
    },
    {
      "c": "Lesotho",
      "iso": "LSO",
      "reg": 2,
      "f": 1.9,
      "t": 51.7,
      "p": 0.16,
      "poly": 0.566
    },
    {
      "c": "Lithuania",
      "iso": "LTU",
      "reg": 3,
      "f": 5.71,
      "t": 52.6,
      "p": -2.84,
      "poly": 0.825
    },
    {
      "c": "Luxembourg",
      "iso": "LUX",
      "reg": 3,
      "f": 2.1,
      "t": 90.9,
      "p": -2.32,
      "poly": 0.874
    },
    {
      "c": "Latvia",
      "iso": "LVA",
      "reg": 2,
      "f": 3.14,
      "t": 61.6,
      "p": -2.48,
      "poly": 0.819
    },
    {
      "c": "Morocco",
      "iso": "MAR",
      "reg": 0,
      "f": 2.14,
      "t": 44.3,
      "p": -0.67,
      "poly": 0.256
    },
    {
      "c": "Monaco",
      "iso": "MCO",
      "reg": null,
      "f": 2,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Moldova",
      "iso": "MDA",
      "reg": 2,
      "f": 4,
      "t": 59.3,
      "p": -0.23,
      "poly": 0.537
    },
    {
      "c": "Madagascar",
      "iso": "MDG",
      "reg": 1,
      "f": 3.95,
      "t": 58.7,
      "p": 1.05,
      "poly": 0.425
    },
    {
      "c": "Maldives",
      "iso": "MDV",
      "reg": 1,
      "f": 4.38,
      "t": 81,
      "p": 0.54,
      "poly": 0.38
    },
    {
      "c": "Mexico",
      "iso": "MEX",
      "reg": 2,
      "f": 3.33,
      "t": 57.6,
      "p": 0.03,
      "poly": 0.662
    },
    {
      "c": "Marshall Islands",
      "iso": "MHL",
      "reg": null,
      "f": 2.52,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Macedonia (FYROM)",
      "iso": "MKD",
      "reg": 2,
      "f": 4.9,
      "t": 58.2,
      "p": 1.08,
      "poly": 0.53
    },
    {
      "c": "Mali",
      "iso": "MLI",
      "reg": 2,
      "f": 4.05,
      "t": 40.4,
      "p": 0.33,
      "poly": 0.545
    },
    {
      "c": "Malta",
      "iso": "MLT",
      "reg": 2,
      "f": 2.29,
      "t": 93.5,
      "p": 1.06,
      "poly": 0.789
    },
    {
      "c": "Myanmar",
      "iso": "MMR",
      "reg": 0,
      "f": 0.81,
      "t": 73,
      "p": 1.42,
      "poly": 0.224
    },
    {
      "c": "Montenegro",
      "iso": "MNE",
      "reg": 1,
      "f": 3.54,
      "t": 69,
      "p": 0.82,
      "poly": 0.478
    },
    {
      "c": "Mongolia",
      "iso": "MNG",
      "reg": 2,
      "f": 5,
      "t": 74.3,
      "p": 0.14,
      "poly": 0.672
    },
    {
      "c": "Mozambique",
      "iso": "MOZ",
      "reg": 1,
      "f": 2,
      "t": 45.3,
      "p": -0.82,
      "poly": 0.43
    },
    {
      "c": "Mauritania",
      "iso": "MRT",
      "reg": 1,
      "f": 4.14,
      "t": 65.6,
      "p": -0.97,
      "poly": 0.38
    },
    {
      "c": "Mauritius",
      "iso": "MUS",
      "reg": 3,
      "f": 2.14,
      "t": 78.3,
      "p": 0.79,
      "poly": 0.728
    },
    {
      "c": "Malawi",
      "iso": "MWI",
      "reg": 1,
      "f": 2.14,
      "t": 70.4,
      "p": -0.84,
      "poly": 0.498
    },
    {
      "c": "Malaysia",
      "iso": "MYS",
      "reg": 1,
      "f": 2.14,
      "t": 79.3,
      "p": 1.12,
      "poly": 0.335
    },
    {
      "c": "Namibia",
      "iso": "NAM",
      "reg": 2,
      "f": 2,
      "t": 72.5,
      "p": -0.62,
      "poly": 0.66
    },
    {
      "c": "Niger",
      "iso": "NER",
      "reg": 2,
      "f": 4.14,
      "t": 57.2,
      "p": -0.97,
      "poly": 0.544
    },
    {
      "c": "Nigeria",
      "iso": "NGA",
      "reg": 1,
      "f": 4.24,
      "t": 51.7,
      "p": -0.91,
      "poly": 0.48
    },
    {
      "c": "Nicaragua",
      "iso": "NIC",
      "reg": 1,
      "f": 1.95,
      "t": 70.2,
      "p": 0.24,
      "poly": 0.427
    },
    {
      "c": "Netherlands",
      "iso": "NLD",
      "reg": 3,
      "f": 3.1,
      "t": 78.6,
      "p": -1.31,
      "poly": 0.868
    },
    {
      "c": "Norway",
      "iso": "NOR",
      "reg": 3,
      "f": 2.48,
      "t": 77.1,
      "p": -2.29,
      "poly": 0.893
    },
    {
      "c": "Nepal",
      "iso": "NPL",
      "reg": 1,
      "f": 1.71,
      "t": 70.1,
      "p": 1,
      "poly": 0.447
    },
    {
      "c": "Nauru",
      "iso": "NRU",
      "reg": null,
      "f": 4.71,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "New Zealand",
      "iso": "NZL",
      "reg": 3,
      "f": 3.33,
      "t": 78.6,
      "p": -2.52,
      "poly": 0.886
    },
    {
      "c": "Oman",
      "iso": "OMN",
      "reg": 0,
      "f": 2.11,
      "t": 61.1,
      "p": -2.04,
      "poly": 0.166
    },
    {
      "c": "Pakistan",
      "iso": "PAK",
      "reg": 1,
      "f": 2.43,
      "t": 52.5,
      "p": -0.78,
      "poly": 0.383
    },
    {
      "c": "Panama",
      "iso": "PAN",
      "reg": 2,
      "f": 2.05,
      "t": 73.8,
      "p": -0.87,
      "poly": 0.739
    },
    {
      "c": "Peru",
      "iso": "PER",
      "reg": 2,
      "f": 2.52,
      "t": 82.9,
      "p": -0.05,
      "poly": 0.782
    },
    {
      "c": "Philippines",
      "iso": "PHL",
      "reg": 2,
      "f": 3.33,
      "t": 75.8,
      "p": -1.15,
      "poly": 0.51
    },
    {
      "c": "Palau",
      "iso": "PLW",
      "reg": null,
      "f": 3.38,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Papua New Guinea",
      "iso": "PNG",
      "reg": 1,
      "f": 2,
      "t": 64.3,
      "p": -1.56,
      "poly": 0.476
    },
    {
      "c": "Poland",
      "iso": "POL",
      "reg": 3,
      "f": 4.81,
      "t": 55.7,
      "p": 1.53,
      "poly": 0.836
    },
    {
      "c": "North Korea",
      "iso": "PRK",
      "reg": 0,
      "f": 1.67,
      "t": 100,
      "p": -1,
      "poly": 0.084
    },
    {
      "c": "Portugal",
      "iso": "PRT",
      "reg": 3,
      "f": 5,
      "t": 56.6,
      "p": -2.22,
      "poly": 0.887
    },
    {
      "c": "Paraguay",
      "iso": "PRY",
      "reg": 2,
      "f": 2.52,
      "t": 63.5,
      "p": -1.15,
      "poly": 0.591
    },
    {
      "c": "Romania",
      "iso": "ROU",
      "reg": 2,
      "f": 4.33,
      "t": 50.1,
      "p": 0.2,
      "poly": 0.66
    },
    {
      "c": "Russia (Soviet Union)",
      "iso": "RUS",
      "reg": 1,
      "f": 4.81,
      "t": 62.5,
      "p": 0.23,
      "poly": 0.304
    },
    {
      "c": "Rwanda",
      "iso": "RWA",
      "reg": 1,
      "f": 2.62,
      "t": 97.1,
      "p": 0.74,
      "poly": 0.197
    },
    {
      "c": "Saudi Arabia",
      "iso": "SAU",
      "reg": 0,
      "f": 1,
      "t": null,
      "p": -1.3,
      "poly": 0.015
    },
    {
      "c": "Sudan",
      "iso": "SDN",
      "reg": 1,
      "f": 1.52,
      "t": 59.2,
      "p": 1.04,
      "poly": 0.203
    },
    {
      "c": "Senegal",
      "iso": "SEN",
      "reg": 2,
      "f": 3.71,
      "t": 62.7,
      "p": -1.1,
      "poly": 0.692
    },
    {
      "c": "Singapore",
      "iso": "SGP",
      "reg": 1,
      "f": 2.76,
      "t": 94.5,
      "p": -1,
      "poly": 0.397
    },
    {
      "c": "Solomon Islands",
      "iso": "SLB",
      "reg": 2,
      "f": 2.33,
      "t": 65.7,
      "p": -1.56,
      "poly": 0.531
    },
    {
      "c": "Sierra Leone",
      "iso": "SLE",
      "reg": 2,
      "f": 1.81,
      "t": 83.2,
      "p": 0.39,
      "poly": 0.492
    },
    {
      "c": "El Salvador",
      "iso": "SLV",
      "reg": 2,
      "f": 5.14,
      "t": 50.6,
      "p": 0.83,
      "poly": 0.592
    },
    {
      "c": "San Marino",
      "iso": "SMR",
      "reg": null,
      "f": 2.71,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Somalia",
      "iso": "SOM",
      "reg": 0,
      "f": 0,
      "t": null,
      "p": 2.25,
      "poly": 0.172
    },
    {
      "c": "Serbia",
      "iso": "SRB",
      "reg": 2,
      "f": 5.52,
      "t": 57.6,
      "p": -0.14,
      "poly": 0.528
    },
    {
      "c": "Sao Tome and Principe",
      "iso": "STP",
      "reg": 2,
      "f": 4.52,
      "t": 73.3,
      "p": -2.05,
      "poly": 0.671
    },
    {
      "c": "Surinam",
      "iso": "SUR",
      "reg": 2,
      "f": 2.1,
      "t": 66.8,
      "p": -1.2,
      "poly": 0.767
    },
    {
      "c": "Slovakia",
      "iso": "SVK",
      "reg": 3,
      "f": 4.14,
      "t": 56.7,
      "p": -0.75,
      "poly": 0.842
    },
    {
      "c": "Slovenia",
      "iso": "SVN",
      "reg": 3,
      "f": 4.67,
      "t": 58.7,
      "p": 0.48,
      "poly": 0.841
    },
    {
      "c": "Sweden",
      "iso": "SWE",
      "reg": 3,
      "f": 2.52,
      "t": 83.9,
      "p": -2.1,
      "poly": 0.913
    },
    {
      "c": "Swaziland",
      "iso": "SWZ",
      "reg": 0,
      "f": 2,
      "t": 60.5,
      "p": 1.31,
      "poly": 0.129
    },
    {
      "c": "Seychelles",
      "iso": "SYC",
      "reg": 2,
      "f": 4.05,
      "t": 88,
      "p": 0.33,
      "poly": 0.488
    },
    {
      "c": "Syria",
      "iso": "SYR",
      "reg": 1,
      "f": 3.76,
      "t": 67,
      "p": 2.02,
      "poly": 0.144
    },
    {
      "c": "Chad",
      "iso": "TCD",
      "reg": 1,
      "f": 3.24,
      "t": 57.8,
      "p": 1.71,
      "poly": 0.279
    },
    {
      "c": "Togo",
      "iso": "TGO",
      "reg": 1,
      "f": 4.38,
      "t": 70.1,
      "p": 1.64,
      "poly": 0.394
    },
    {
      "c": "Thailand",
      "iso": "THA",
      "reg": 1,
      "f": 4.95,
      "t": 70,
      "p": 1.66,
      "poly": 0.354
    },
    {
      "c": "Tajikistan",
      "iso": "TJK",
      "reg": 1,
      "f": 3.57,
      "t": 89.6,
      "p": -0.99,
      "poly": 0.215
    },
    {
      "c": "Turkmenistan",
      "iso": "TKM",
      "reg": 0,
      "f": 4.14,
      "t": 92.4,
      "p": -2.37,
      "poly": 0.12
    },
    {
      "c": "East Timor",
      "iso": "TLS",
      "reg": 2,
      "f": 3.5,
      "t": 79.2,
      "p": -0.23,
      "poly": 0.65
    },
    {
      "c": "Tonga",
      "iso": "TON",
      "reg": null,
      "f": 3.29,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Trinidad and Tobago",
      "iso": "TTO",
      "reg": 3,
      "f": 3,
      "t": 65.6,
      "p": -2.04,
      "poly": 0.758
    },
    {
      "c": "Tunisia",
      "iso": "TUN",
      "reg": 1,
      "f": 2.9,
      "t": 79.1,
      "p": 0.69,
      "poly": 0.43
    },
    {
      "c": "Turkey",
      "iso": "TUR",
      "reg": 2,
      "f": 3.19,
      "t": 82.8,
      "p": 1.84,
      "poly": 0.499
    },
    {
      "c": "Tuvalu",
      "iso": "TUV",
      "reg": null,
      "f": 2.48,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Taiwan",
      "iso": "TWN",
      "reg": 3,
      "f": 5.1,
      "t": 65,
      "p": -1.77,
      "poly": 0.802
    },
    {
      "c": "Tanzania",
      "iso": "TZA",
      "reg": 1,
      "f": 2,
      "t": 63.5,
      "p": -1.09,
      "poly": 0.446
    },
    {
      "c": "Uganda",
      "iso": "UGA",
      "reg": 1,
      "f": 2.9,
      "t": 66.6,
      "p": -0.03,
      "poly": 0.308
    },
    {
      "c": "Ukraine",
      "iso": "UKR",
      "reg": 1,
      "f": 4.9,
      "t": 66.4,
      "p": 0.1,
      "poly": 0.473
    },
    {
      "c": "Uruguay",
      "iso": "URY",
      "reg": 3,
      "f": 2,
      "t": 89.7,
      "p": -3.1,
      "poly": 0.892
    },
    {
      "c": "United States",
      "iso": "USA",
      "reg": 3,
      "f": 5,
      "t": 61.9,
      "p": 0.4,
      "poly": 0.868
    },
    {
      "c": "Uzbekistan",
      "iso": "UZB",
      "reg": 1,
      "f": 4.29,
      "t": 83.3,
      "p": -2.12,
      "poly": 0.168
    },
    {
      "c": "Saint Vincent and the Grenadines",
      "iso": "VCT",
      "reg": null,
      "f": 2.33,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Venezuela",
      "iso": "VEN",
      "reg": 1,
      "f": 5,
      "t": 57.4,
      "p": 1.67,
      "poly": 0.386
    },
    {
      "c": "Democratic Republic of Vietnam",
      "iso": "VNM",
      "reg": 0,
      "f": 2.1,
      "t": 99.4,
      "p": -0.79,
      "poly": 0.155
    },
    {
      "c": "Vanuatu",
      "iso": "VUT",
      "reg": 2,
      "f": 2.81,
      "t": 62.2,
      "p": -1.29,
      "poly": 0.694
    },
    {
      "c": "Samoa",
      "iso": "WSM",
      "reg": null,
      "f": 1.71,
      "t": null,
      "p": null,
      "poly": null
    },
    {
      "c": "Yemen",
      "iso": "YEM",
      "reg": 1,
      "f": 2.29,
      "t": 68.3,
      "p": 1.54,
      "poly": 0.244
    },
    {
      "c": "South Africa",
      "iso": "ZAF",
      "reg": 3,
      "f": 2,
      "t": 73.4,
      "p": 0.09,
      "poly": 0.754
    },
    {
      "c": "Zambia",
      "iso": "ZMB",
      "reg": 1,
      "f": 2.76,
      "t": 54.4,
      "p": 0.06,
      "poly": 0.465
    },
    {
      "c": "Zimbabwe",
      "iso": "ZWE",
      "reg": 1,
      "f": 2.95,
      "t": 55.4,
      "p": 2.29,
      "poly": 0.274
    }
  ],
  "cors": {
    "turnout": {
      "r": -0.233,
      "p": 0.0026,
      "n": 166
    },
    "polar": {
      "r": -0.03,
      "p": 0.701,
      "n": 168
    }
  },
  "yearly": [
    {
      "y": 1945,
      "n": 24
    },
    {
      "y": 1946,
      "n": 29
    },
    {
      "y": 1947,
      "n": 19
    },
    {
      "y": 1948,
      "n": 21
    },
    {
      "y": 1949,
      "n": 26
    },
    {
      "y": 1950,
      "n": 27
    },
    {
      "y": 1951,
      "n": 23
    },
    {
      "y": 1952,
      "n": 20
    },
    {
      "y": 1953,
      "n": 29
    },
    {
      "y": 1954,
      "n": 24
    },
    {
      "y": 1955,
      "n": 19
    },
    {
      "y": 1956,
      "n": 23
    },
    {
      "y": 1957,
      "n": 30
    },
    {
      "y": 1958,
      "n": 40
    },
    {
      "y": 1959,
      "n": 18
    },
    {
      "y": 1960,
      "n": 30
    },
    {
      "y": 1961,
      "n": 30
    },
    {
      "y": 1962,
      "n": 28
    },
    {
      "y": 1963,
      "n": 33
    },
    {
      "y": 1964,
      "n": 33
    },
    {
      "y": 1965,
      "n": 39
    },
    {
      "y": 1966,
      "n": 29
    },
    {
      "y": 1967,
      "n": 28
    },
    {
      "y": 1968,
      "n": 30
    },
    {
      "y": 1969,
      "n": 32
    },
    {
      "y": 1970,
      "n": 38
    },
    {
      "y": 1971,
      "n": 31
    },
    {
      "y": 1972,
      "n": 28
    },
    {
      "y": 1973,
      "n": 35
    },
    {
      "y": 1974,
      "n": 32
    },
    {
      "y": 1975,
      "n": 26
    },
    {
      "y": 1976,
      "n": 28
    },
    {
      "y": 1977,
      "n": 39
    },
    {
      "y": 1978,
      "n": 41
    },
    {
      "y": 1979,
      "n": 45
    },
    {
      "y": 1980,
      "n": 34
    },
    {
      "y": 1981,
      "n": 39
    },
    {
      "y": 1982,
      "n": 41
    },
    {
      "y": 1983,
      "n": 41
    },
    {
      "y": 1984,
      "n": 40
    },
    {
      "y": 1985,
      "n": 39
    },
    {
      "y": 1986,
      "n": 37
    },
    {
      "y": 1987,
      "n": 48
    },
    {
      "y": 1988,
      "n": 39
    },
    {
      "y": 1989,
      "n": 49
    },
    {
      "y": 1990,
      "n": 46
    },
    {
      "y": 1991,
      "n": 53
    },
    {
      "y": 1992,
      "n": 63
    },
    {
      "y": 1993,
      "n": 65
    },
    {
      "y": 1994,
      "n": 55
    },
    {
      "y": 1995,
      "n": 54
    },
    {
      "y": 1996,
      "n": 62
    },
    {
      "y": 1997,
      "n": 55
    },
    {
      "y": 1998,
      "n": 60
    },
    {
      "y": 1999,
      "n": 63
    },
    {
      "y": 2000,
      "n": 58
    },
    {
      "y": 2001,
      "n": 55
    },
    {
      "y": 2002,
      "n": 64
    },
    {
      "y": 2003,
      "n": 54
    },
    {
      "y": 2004,
      "n": 61
    },
    {
      "y": 2005,
      "n": 55
    },
    {
      "y": 2006,
      "n": 65
    },
    {
      "y": 2007,
      "n": 68
    },
    {
      "y": 2008,
      "n": 60
    },
    {
      "y": 2009,
      "n": 59
    },
    {
      "y": 2010,
      "n": 63
    },
    {
      "y": 2011,
      "n": 66
    },
    {
      "y": 2012,
      "n": 59
    },
    {
      "y": 2013,
      "n": 58
    },
    {
      "y": 2014,
      "n": 60
    },
    {
      "y": 2015,
      "n": 61
    },
    {
      "y": 2016,
      "n": 65
    },
    {
      "y": 2017,
      "n": 44
    },
    {
      "y": 2018,
      "n": 60
    },
    {
      "y": 2019,
      "n": 68
    },
    {
      "y": 2020,
      "n": 65
    },
    {
      "y": 2021,
      "n": 65
    },
    {
      "y": 2022,
      "n": 57
    },
    {
      "y": 2023,
      "n": 63
    },
    {
      "y": 2024,
      "n": 79
    }
  ],
  "robust": [
    {
      "outcome": "Turnout (registered)",
      "label": "Polling occasions, 10-yr",
      "est": -2.866,
      "lo": -4.099,
      "hi": -1.633,
      "p": 8.8e-06,
      "panel": "turnout"
    },
    {
      "outcome": "Turnout (registered)",
      "label": "Contests (runoffs folded), 10-yr",
      "est": -1.724,
      "lo": -2.665,
      "hi": -0.783,
      "p": 0.0004,
      "panel": "turnout"
    },
    {
      "outcome": "Turnout (registered)",
      "label": "Polling occasions, 5-yr",
      "est": -2.215,
      "lo": -3.258,
      "hi": -1.172,
      "p": 0,
      "panel": "turnout"
    },
    {
      "outcome": "Turnout (registered)",
      "label": "Cumulative exposure",
      "est": -2.209,
      "lo": -5.551,
      "hi": 1.132,
      "p": 0.194,
      "panel": "turnout"
    },
    {
      "outcome": "Turnout (VAP)",
      "label": "Polling occasions, 10-yr",
      "est": -1.719,
      "lo": -2.905,
      "hi": -0.533,
      "p": 0.0048,
      "panel": "turnout"
    },
    {
      "outcome": "Polarization",
      "label": "Polling occasions, 10-yr",
      "est": 0.108,
      "lo": 0.041,
      "hi": 0.174,
      "p": 0.0018,
      "panel": "division"
    },
    {
      "outcome": "Polarization",
      "label": "Contests (runoffs folded), 10-yr",
      "est": 0.097,
      "lo": 0.036,
      "hi": 0.158,
      "p": 0.0019,
      "panel": "division"
    },
    {
      "outcome": "Polarization",
      "label": "Polling occasions, 5-yr",
      "est": 0.075,
      "lo": 0.027,
      "hi": 0.124,
      "p": 0.0024,
      "panel": "division"
    },
    {
      "outcome": "Polarization",
      "label": "Cumulative exposure",
      "est": 0.217,
      "lo": -0.034,
      "hi": 0.468,
      "p": 0.0903,
      "panel": "division"
    },
    {
      "outcome": "Societal polarization",
      "label": "Polling occasions, 10-yr",
      "est": -0.123,
      "lo": -0.199,
      "hi": -0.047,
      "p": 0.0017,
      "panel": "division"
    }
  ],
  "imp": [
    {
      "analysis": "Division (polarization)",
      "method": "Complete case",
      "est": 0.052,
      "lo": -0.001,
      "hi": 0.105,
      "se": 0.027,
      "p": 0.0554
    },
    {
      "analysis": "Division (polarization)",
      "method": "Multiple imputation",
      "est": 0.075,
      "lo": 0.032,
      "hi": 0.118,
      "se": 0.022,
      "p": 0.0006
    },
    {
      "analysis": "Indifference (turnout)",
      "method": "Complete case",
      "est": -1.74,
      "lo": -2.487,
      "hi": -0.992,
      "se": 0.381,
      "p": 9.91e-06
    },
    {
      "analysis": "Indifference (turnout)",
      "method": "Multiple imputation",
      "est": -2.099,
      "lo": -2.813,
      "hi": -1.385,
      "se": 0.364,
      "p": 8.67e-09
    }
  ]
};

